version: '3.8'
services:
  zoo-api:
    build:
      context: zoo/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    container_name: zoo-app
    restart: unless-stopped
    networks:
      - zoo-network

networks:
  zoo-network:
    driver: bridge