name: CI/CD Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Docker Compose
        run: |
          echo "Building application with Docker Compose..."
          docker compose -f docker-compose.yml build
          echo "✅ Build successful!"

      - name: Run Unit Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/zoo:/app \
            -w /app maven:3.9.8-eclipse-temurin-21 \
            mvn clean test

      - name: Build Production Image
        run: |
          docker build -t zoo-api:latest zoo/
          
      - name: Ready for Deployment
        if: github.ref == 'refs/heads/development'
        run: |
          echo "✅ Build successful!"
          echo "✅ Tests passed!"
          echo "Ready for deployment to hosting platform."

      - name: Deploy to Render
        if: github.ref == 'refs/heads/development'
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "do_not_clear"}' \
            https://api.render.com/v1/services/srv-d2qs7ure5dus73cgsba0/deploys
          
