name: CI/CD Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Test with Docker Compose (as you prefer)
      - name: Build & Test with Docker Compose
        run: |
          docker compose -f docker compose.yml up --build -d
          # Wait for services to be ready
          sleep 30
          # Run tests (adjust URL as needed)
          curl -f http://localhost:8080/actuator/health || exit 1
          # Stop services
          docker compose down

      # 3️⃣ Build production Docker image (single service for deployment)
      - name: Build Production Image
        run: |
          docker build -f zoo/Dockerfile.prod -t zoo-api:latest zoo/

      # 4️⃣ Deploy notification
      - name: Ready for Deployment
        if: github.ref == 'refs/heads/development'
        run: |
          echo "✅ Tests passed with Docker Compose!"
          echo "✅ Production image built successfully!"
          echo "Ready for deployment to hosting platform."
